"""initial_schema

Revision ID: 146f8e7efe38
Revises: 
Create Date: 2026-09-04 04:54:59.092806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


# revision identifiers, used by Alembic.
revision: str = '146f8e7efe38'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('officer', 'supervisor', 'admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('actor_user_id', app.models.base.UUID(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('before_value', sa.JSON(), nullable=True),
    sa.Column('after_value', sa.JSON(), nullable=True),
    sa.Column('prev_hash', sa.Text(), nullable=True),
    sa.Column('entry_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_actor', 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index('idx_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_entry_hash', 'audit_logs', ['entry_hash'], unique=False)
    op.create_table('batch_sessions',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('officer_id', app.models.base.UUID(), nullable=False),
    sa.Column('session_name', sa.Text(), nullable=False),
    sa.Column('premises_name', sa.Text(), nullable=True),
    sa.Column('premises_address', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'completed', 'archived')", name='ck_batch_sessions_status'),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_batch_sessions_created', 'batch_sessions', ['created_at'], unique=False)
    op.create_index('idx_batch_sessions_officer', 'batch_sessions', ['officer_id'], unique=False)
    op.create_index('idx_batch_sessions_status', 'batch_sessions', ['status'], unique=False)
    op.create_table('rule_packs',
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_citation', sa.Text(), nullable=True),
    sa.Column('rules_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', app.models.base.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('inspections',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('officer_id', app.models.base.UUID(), nullable=False),
    sa.Column('batch_id', app.models.base.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('commodity_category', sa.Text(), nullable=True),
    sa.Column('rule_pack_version', sa.Text(), nullable=False),
    sa.Column('is_self_check', sa.Boolean(), nullable=False),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('captured_offline', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_id', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('draft','processing','needs_review','completed','sync_pending')", name='ck_inspections_status'),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_sessions.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inspections_batch', 'inspections', ['batch_id'], unique=False)
    op.create_index('idx_inspections_client_id', 'inspections', ['client_id'], unique=False)
    op.create_index('idx_inspections_created', 'inspections', ['created_at'], unique=False)
    op.create_index('idx_inspections_officer', 'inspections', ['officer_id'], unique=False)
    op.create_index('idx_inspections_status', 'inspections', ['status'], unique=False)
    op.create_table('inspection_images',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('inspection_id', app.models.base.UUID(), nullable=False),
    sa.Column('image_role', sa.Text(), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=False),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('calibration_scale_mm_per_px', sa.Numeric(), nullable=True),
    sa.Column('quality_check_passed', sa.Boolean(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=True),
    sa.Column('sha256_hash', sa.Text(), nullable=True),
    sa.CheckConstraint("image_role IN ('front_pdp','back_panel','side_panel','sticker','ecommerce_listing')", name='ck_images_role'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_images_client_id', 'inspection_images', ['client_id'], unique=False)
    op.create_index('idx_images_inspection', 'inspection_images', ['inspection_id'], unique=False)
    op.create_index('idx_images_sha256', 'inspection_images', ['sha256_hash'], unique=False)
    op.create_table('reports',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('inspection_id', app.models.base.UUID(), nullable=False),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=False),
    sa.Column('generated_by', app.models.base.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("format IN ('pdf','editable')", name='ck_reports_format'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reports_inspection', 'reports', ['inspection_id'], unique=False)
    op.create_table('extracted_fields',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('inspection_id', app.models.base.UUID(), nullable=False),
    sa.Column('source_image_id', app.models.base.UUID(), nullable=False),
    sa.Column('field_type', sa.Text(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsed_value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(), nullable=False),
    sa.Column('bounding_box', sa.JSON(), nullable=False),
    sa.Column('verdict', sa.Text(), nullable=False),
    sa.Column('reviewed_by_officer', sa.Boolean(), nullable=False),
    sa.Column('officer_override_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("verdict IN ('pass','fail','needs_review','not_applicable')", name='ck_fields_verdict'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_image_id'], ['inspection_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fields_inspection', 'extracted_fields', ['inspection_id'], unique=False)
    op.create_index('idx_fields_verdict', 'extracted_fields', ['verdict'], unique=False)
    op.create_table('violations',
    sa.Column('id', app.models.base.UUID(), nullable=False),
    sa.Column('inspection_id', app.models.base.UUID(), nullable=False),
    sa.Column('extracted_field_id', app.models.base.UUID(), nullable=True),
    sa.Column('rule_id', sa.Text(), nullable=False),
    sa.Column('rule_pack_version', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('citation', sa.Text(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("severity IN ('minor','major','critical')", name='ck_violations_severity'),
    sa.ForeignKeyConstraint(['extracted_field_id'], ['extracted_fields.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_violations_inspection', 'violations', ['inspection_id'], unique=False)
    op.create_index('idx_violations_rule', 'violations', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_violations_rule', table_name='violations')
    op.drop_index('idx_violations_inspection', table_name='violations')
    op.drop_table('violations')
    op.drop_index('idx_fields_verdict', table_name='extracted_fields')
    op.drop_index('idx_fields_inspection', table_name='extracted_fields')
    op.drop_table('extracted_fields')
    op.drop_index('idx_reports_inspection', table_name='reports')
    op.drop_table('reports')
    op.drop_index('idx_images_sha256', table_name='inspection_images')
    op.drop_index('idx_images_inspection', table_name='inspection_images')
    op.drop_index('idx_images_client_id', table_name='inspection_images')
    op.drop_table('inspection_images')
    op.drop_index('idx_inspections_status', table_name='inspections')
    op.drop_index('idx_inspections_officer', table_name='inspections')
    op.drop_index('idx_inspections_created', table_name='inspections')
    op.drop_index('idx_inspections_client_id', table_name='inspections')
    op.drop_index('idx_inspections_batch', table_name='inspections')
    op.drop_table('inspections')
    op.drop_table('rule_packs')
    op.drop_index('idx_batch_sessions_status', table_name='batch_sessions')
    op.drop_index('idx_batch_sessions_officer', table_name='batch_sessions')
    op.drop_index('idx_batch_sessions_created', table_name='batch_sessions')
    op.drop_table('batch_sessions')
    op.drop_index('idx_audit_entry_hash', table_name='audit_logs')
    op.drop_index('idx_audit_entity', table_name='audit_logs')
    op.drop_index('idx_audit_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
